/****************************************************************************
 * Copyright 2018, Optimizely, Inc. and contributors                        *
 *                                                                          *
 * Licensed under the Apache License, Version 2.0 (the "License");          *
 * you may not use this file except in compliance with the License.         *
 * You may obtain a copy of the License at                                  *
 *                                                                          *
 *    http://www.apache.org/licenses/LICENSE-2.0                            *
 *                                                                          *
 * Unless required by applicable law or agreed to in writing, software      *
 * distributed under the License is distributed on an "AS IS" BASIS,        *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. *
 * See the License for the specific language governing permissions and      *
 * limitations under the License.                                           *
 ***************************************************************************/

#import "OPTLYNSObject+Validation.h"

@implementation NSObject (Validation)

- (nullable NSString *)getValidString {
    if (self) {
        if ([self isKindOfClass:[NSString class]] && ![(NSString *)self isEqualToString:@""]) {
            return (NSString *)self;
        }
    }
    return nil;
}

- (nullable NSArray *)getValidArray {
    if (self) {
        if ([self isKindOfClass:[NSArray class]] && (((NSArray *)self).count > 0)) {
            return (NSArray *)self;
        }
    }
    return nil;
}

- (nullable NSDictionary *)getValidDictionary {
    if (self) {
        if ([self isKindOfClass:[NSDictionary class]] && (((NSDictionary *)self).count > 0)) {
            return (NSDictionary *)self;
        }
    }
    return nil;
}

- (NSString *)getStringOrEmpty {
    NSString *string = @"";
    if (self) {
        if ([self isKindOfClass:[NSString class]]) {
            string = [string stringByAppendingString:((NSString *)self)];
        }
    }
    return string;
}

-(BOOL)isNumeric {
    //Check if given object is acceptable numeric type
    if (self) {
        if ([self isBool]) {
            return false;
        }
        else if ([self isKindOfClass:[NSNumber class]]) {
            // Require real numbers (not infinite or NaN).
            double doubleValue = [(NSNumber*)self doubleValue];
            if (isfinite(doubleValue)) {
                return true;
            } else {
                return false;
            }
        }
    }
    return false;
}

-(BOOL)isBool {
    //Check if given object is acceptable boolean type
    if (self) {
        if ([self isKindOfClass:[NSNumber class]]) {
            NSNumber *number = (NSNumber*)self;
            const char *objCType = [number objCType];
            // Dispatch objCType according to one of "Type Encodings" listed here:
            // https://developer.apple.com/library/content/documentation/Cocoa/Conceptual/ObjCRuntimeGuide/Articles/ocrtTypeEncodings.html
            if ((strcmp(objCType, @encode(bool)) == 0)
                || [self isEqual:@YES]
                || [self isEqual:@NO]) {
                // NSNumber's generated by "+ (NSNumber *)numberWithBool:(BOOL)value;"
                // serialize to JSON booleans "true" and "false" via NSJSONSerialization .
                // The @YES and @NO compile to __NSCFBoolean's which (strangely enough)
                // are ((strcmp(objCType, @encode(char)) == 0) but these serialize as
                // JSON booleans "true" and "false" instead of JSON numbers.
                // These aren't integers, so shouldn't be sent.
                return true;
            }
        }
    }
    return false;
}
@end
